name: Release - close version
on:
  workflow_dispatch:

jobs:

  close-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
      - name: Execute close version script
        run: bash .config/ci/release-close-version.sh
