name: Release - next version
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:

  close-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: execute next version script
        run: bash .config/ci/release-next-minor-version.sh
      - name: Git push
        run: |
          git push
